In [1]:
from influxdb import InfluxDBClient
from datetime import datetime as dt
import numpy as np
from collections import defaultdict
import csv
import pandas as pd
import matplotlib.pylab as plt
# ######### Here we are loading the export data ##############
temp_bill = []
temp_dates = []
with open('NEM12_8002180729_01-MAY-16-06-JUN-17.csv', 'r') as billCSV:
	data = csv.reader(billCSV)
	takeValues = False
	for each in data:
		if each[0] == '100':
			continue
		elif each[0] == '200':
			if each[7] == 'KWH':
				takeValues = True
				if each[4] == 'B1':
					ty = 'export'
				else:
					ty = 'import'
			else:
				takeValues = False
		elif each[0] == '300' and takeValues:    
			k = each[2: each.index('A')]
			k.append(ty)
			temp_bill.append(k)           
			temp_dates.append(each[1])

# for each in temp_bill:
# 	print(each)
# 	print()

temp_cols = ['00:00', '00:30', '01:00', '01:30', '02:00', '02:30', '03:00', '03:30', '04:00', '04:30', '05:00', '05:30',
			'06:00', '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
			'12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30',
			'18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00', '22:30', '23:00', '23:30', "Import_Export"]
billData = pd.DataFrame(temp_bill, index=temp_dates, columns=temp_cols)
billData.index = pd.to_datetime(billData.index)
billData['weekday'] = billData.index.weekday.values

In [2]:
billData

,00:00,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,Import_Export,weekday
2016-05-01,13.904,14.448,13.552,14.688,13.648,14.912,13.888,15.152,14.336,15.632,...,14.208,13.04,14.144,13.088,14.368,13.44,14.416,13.552,import,6
2016-05-02,14.56,13.52,14.624,13.68,14.4,13.84,14.16,13.664,14.592,14.848,...,13.52,13.312,13.152,14.72,13.552,13.44,13.296,13.296,import,0
2016-05-03,13.488,13.616,13.76,13.888,13.792,13.888,13.84,14.112,14.336,14.304,...,14.064,13.984,13.248,13.472,13.264,13.392,13.136,13.232,import,1
2016-05-04,13.072,13.36,13.376,13.2,13.744,13.712,13.696,13.92,14.096,13.344,...,13.28,13.168,13.184,13.344,13.424,13.248,13.472,13.392,import,2
2016-05-05,13.52,13.552,13.552,13.552,13.712,13.728,13.776,13.952,14.224,14.224,...,14.576,14.112,14.128,14.352,14.112,14.256,14.336,14.192,import,3
2016-05-06,14.416,14.08,14,14.064,14.208,14.176,14.272,14.368,14.672,14.72,...,12.528,13.872,12.304,12.544,12.496,12.416,12.4,12.512,import,4
2016-05-07,12.272,12.56,12.496,12.544,12.464,12.496,12.64,12.848,13.088,12.976,...,12.112,10.96,12.272,12.064,12.112,12.416,12.48,12.432,import,5
2016-05-08,12.592,12.288,12.448,12.496,12.48,12.432,12.432,12.624,12.88,12.816,...,12.352,12.448,12.48,11.104,12.064,12.24,12.336,12.32,import,6
2016-05-09,12.448,12.128,12.288,12.48,12.416,12.176,12.736,12.432,12.752,12.656,...,12.128,12.064,12.256,12.368,11.952,11.76,11.936,12.24,import,0
2016-05-10,12.288,12.224,12.24,12.272,12.208,12.272,12.336,11.744,12.736,12.48,...,14.576,15.856,12.352,12.24,12.416,12.384,11.904,12.432,import,1
2016-05-11,12.272,12.096,12.256,12.384,12.368,11.888,11.824,12,12.272,12.496,...,11.872,11.808,12.128,11.808,12,12.128,12.176,12,import,2
2016-05-12,12.128,12.128,12.096,12.128,12.256,12.224,12.192,12.56,12.752,12.864,...,12.112,12.08,11.792,11.936,12.032,12.064,12,12.096,import,3
2016-05-13,11.936,11.888,12.16,12.08,12.048,11.968,12.128,12.24,12.688,12.672,...,12.48,12.576,12.448,12.464,12.624,12.624,12.4,12.384,import,4
2016-05-14,12.64,12.688,12.72,12.768,12.768,12.48,12.704,12.864,13.216,13.296,...,11.488,11.744,11.44,11.68,11.664,11.696,11.456,11.232,import,5
2016-05-15,11.584,12,12,11.808,11.728,12.064,11.888,12.24,12.192,12.752,...,12.048,12.096,12.176,12.096,12.192,12.112,12.16,12.208,import,6
2016-05-16,12.192,12.24,12.016,12.176,12.08,11.984,12.192,12.08,12.624,12.864,...,13.216,12.448,12.8,12.416,12.512,12.864,12.128,12.832,import,0
2016-05-17,11.808,12.88,11.888,13.616,12.416,13.616,12.416,13.728,12.816,14.224,...,12.256,12.192,12.176,12.208,12.288,12.288,12.4,12.288,import,1
2016-05-18,12.176,12.448,12.016,12.176,12.08,11.744,11.696,11.936,11.888,12.176,...,11.92,12.112,12.08,12.432,11.488,12.016,11.888,11.952,import,2
2016-05-19,11.744,11.904,11.92,12.224,12.528,12.528,12.256,12.736,13.056,12.72,...,11.68,11.6,11.488,11.888,12.32,11.36,11.2,11.68,import,3
2016-05-20,11.632,12.096,12.208,12.224,12.112,12.176,12.256,12.336,12.384,12.352,...,12.4,12.592,12.464,12.64,12.528,12.128,12.08,11.936,import,4
2016-05-21,12.064,12.048,12.112,11.936,11.952,11.824,11.904,12.256,12.368,12.48,...,12.128,11.808,11.776,11.648,11.744,11.904,11.744,11.664,import,5
2016-05-22,11.584,11.536,11.872,11.728,10.848,11.792,11.776,12.432,12.24,12.448,...,12.448,12.624,12.464,12.48,12.352,12.304,12.48,12.192,import,6
2016-05-23,12.448,12.368,12.064,11.872,11.952,12,12.08,12.08,12.512,12.608,...,11.808,11.856,11.824,12.336,12.272,12.128,12.208,12.176,import,0
2016-05-24,12.192,12.24,12.336,12.096,12.176,12.16,11.936,11.744,12.192,12.192,...,13.888,13.504,13.68,13.76,13.776,13.136,13.632,13.712,import,1
2016-05-25,13.248,13.216,13.344,13.12,13.136,13.264,13.536,13.536,13.728,13.872,...,12.576,12.8,12.704,12.736,12.816,13.136,12.656,12.528,import,2
2016-05-26,12.56,12.672,12.512,13.136,12.88,12.672,12.688,12.816,12.736,12.672,...,13.68,13.248,13.264,13.264,13.024,13.376,13.392,12.928,import,3
2016-05-27,13.088,13.136,13.456,13.552,13.504,13.488,13.44,13.696,13.648,13.552,...,12.416,12.432,12.608,12.656,12.688,12.656,12.656,12.832,import,4
2016-05-28,12.624,12.816,12.864,12.592,12.832,12.912,12.832,12.704,12.304,12.512,...,12.432,12.272,12.8,12.752,12.896,12.912,12.88,12.864,import,5
2016-05-29,13.008,13.024,12.576,12.32,12.416,12.384,12.48,12.816,12.512,12.432,...,12.336,12.544,12.544,12.592,12.384,12.208,12.288,12.208,import,6
2016-05-30,12.256,12.272,12.384,12.304,12.32,12.336,12.224,12.416,12.352,12.16,...,12.576,12.576,12.704,12.48,11.76,12.064,12.048,12.368,import,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-05-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,6
2017-05-08,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,0
2017-05-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,1
2017-05-10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,2
2017-05-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,3
2017-05-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,4
2017-05-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,5
2017-05-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,6
2017-05-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,0
2017-05-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,1
2017-05-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,2
2017-05-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,3
2017-05-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,4
2017-05-20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,5
2017-05-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,6
2017-05-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,0
2017-05-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,1
2017-05-24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,2
2017-05-25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,3
2017-05-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,4
2017-05-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,5
2017-05-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,6
2017-05-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,0
2017-05-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,1
2017-05-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,2
2017-06-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,3
2017-06-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,4
2017-06-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,5
2017-06-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,6
2017-06-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,export,0

In [3]:
def label_weekday(row):
    return row['weekday'] in [5, 6]

In [4]:
billData['weekend'] = billData.apply(lambda row: label_weekday(row), axis=1)

In [5]:
billData

,00:00,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,20:30,21:00,21:30,22:00,22:30,23:00,23:30,Import_Export,weekday,weekend
2016-05-01,13.904,14.448,13.552,14.688,13.648,14.912,13.888,15.152,14.336,15.632,...,13.04,14.144,13.088,14.368,13.44,14.416,13.552,import,6,True
2016-05-02,14.56,13.52,14.624,13.68,14.4,13.84,14.16,13.664,14.592,14.848,...,13.312,13.152,14.72,13.552,13.44,13.296,13.296,import,0,False
2016-05-03,13.488,13.616,13.76,13.888,13.792,13.888,13.84,14.112,14.336,14.304,...,13.984,13.248,13.472,13.264,13.392,13.136,13.232,import,1,False
2016-05-04,13.072,13.36,13.376,13.2,13.744,13.712,13.696,13.92,14.096,13.344,...,13.168,13.184,13.344,13.424,13.248,13.472,13.392,import,2,False
2016-05-05,13.52,13.552,13.552,13.552,13.712,13.728,13.776,13.952,14.224,14.224,...,14.112,14.128,14.352,14.112,14.256,14.336,14.192,import,3,False
2016-05-06,14.416,14.08,14,14.064,14.208,14.176,14.272,14.368,14.672,14.72,...,13.872,12.304,12.544,12.496,12.416,12.4,12.512,import,4,False
2016-05-07,12.272,12.56,12.496,12.544,12.464,12.496,12.64,12.848,13.088,12.976,...,10.96,12.272,12.064,12.112,12.416,12.48,12.432,import,5,True
2016-05-08,12.592,12.288,12.448,12.496,12.48,12.432,12.432,12.624,12.88,12.816,...,12.448,12.48,11.104,12.064,12.24,12.336,12.32,import,6,True
2016-05-09,12.448,12.128,12.288,12.48,12.416,12.176,12.736,12.432,12.752,12.656,...,12.064,12.256,12.368,11.952,11.76,11.936,12.24,import,0,False
2016-05-10,12.288,12.224,12.24,12.272,12.208,12.272,12.336,11.744,12.736,12.48,...,15.856,12.352,12.24,12.416,12.384,11.904,12.432,import,1,False
2016-05-11,12.272,12.096,12.256,12.384,12.368,11.888,11.824,12,12.272,12.496,...,11.808,12.128,11.808,12,12.128,12.176,12,import,2,False
2016-05-12,12.128,12.128,12.096,12.128,12.256,12.224,12.192,12.56,12.752,12.864,...,12.08,11.792,11.936,12.032,12.064,12,12.096,import,3,False
2016-05-13,11.936,11.888,12.16,12.08,12.048,11.968,12.128,12.24,12.688,12.672,...,12.576,12.448,12.464,12.624,12.624,12.4,12.384,import,4,False
2016-05-14,12.64,12.688,12.72,12.768,12.768,12.48,12.704,12.864,13.216,13.296,...,11.744,11.44,11.68,11.664,11.696,11.456,11.232,import,5,True
2016-05-15,11.584,12,12,11.808,11.728,12.064,11.888,12.24,12.192,12.752,...,12.096,12.176,12.096,12.192,12.112,12.16,12.208,import,6,True
2016-05-16,12.192,12.24,12.016,12.176,12.08,11.984,12.192,12.08,12.624,12.864,...,12.448,12.8,12.416,12.512,12.864,12.128,12.832,import,0,False
2016-05-17,11.808,12.88,11.888,13.616,12.416,13.616,12.416,13.728,12.816,14.224,...,12.192,12.176,12.208,12.288,12.288,12.4,12.288,import,1,False
2016-05-18,12.176,12.448,12.016,12.176,12.08,11.744,11.696,11.936,11.888,12.176,...,12.112,12.08,12.432,11.488,12.016,11.888,11.952,import,2,False
2016-05-19,11.744,11.904,11.92,12.224,12.528,12.528,12.256,12.736,13.056,12.72,...,11.6,11.488,11.888,12.32,11.36,11.2,11.68,import,3,False
2016-05-20,11.632,12.096,12.208,12.224,12.112,12.176,12.256,12.336,12.384,12.352,...,12.592,12.464,12.64,12.528,12.128,12.08,11.936,import,4,False
2016-05-21,12.064,12.048,12.112,11.936,11.952,11.824,11.904,12.256,12.368,12.48,...,11.808,11.776,11.648,11.744,11.904,11.744,11.664,import,5,True
2016-05-22,11.584,11.536,11.872,11.728,10.848,11.792,11.776,12.432,12.24,12.448,...,12.624,12.464,12.48,12.352,12.304,12.48,12.192,import,6,True
2016-05-23,12.448,12.368,12.064,11.872,11.952,12,12.08,12.08,12.512,12.608,...,11.856,11.824,12.336,12.272,12.128,12.208,12.176,import,0,False
2016-05-24,12.192,12.24,12.336,12.096,12.176,12.16,11.936,11.744,12.192,12.192,...,13.504,13.68,13.76,13.776,13.136,13.632,13.712,import,1,False
2016-05-25,13.248,13.216,13.344,13.12,13.136,13.264,13.536,13.536,13.728,13.872,...,12.8,12.704,12.736,12.816,13.136,12.656,12.528,import,2,False
2016-05-26,12.56,12.672,12.512,13.136,12.88,12.672,12.688,12.816,12.736,12.672,...,13.248,13.264,13.264,13.024,13.376,13.392,12.928,import,3,False
2016-05-27,13.088,13.136,13.456,13.552,13.504,13.488,13.44,13.696,13.648,13.552,...,12.432,12.608,12.656,12.688,12.656,12.656,12.832,import,4,False
2016-05-28,12.624,12.816,12.864,12.592,12.832,12.912,12.832,12.704,12.304,12.512,...,12.272,12.8,12.752,12.896,12.912,12.88,12.864,import,5,True
2016-05-29,13.008,13.024,12.576,12.32,12.416,12.384,12.48,12.816,12.512,12.432,...,12.544,12.544,12.592,12.384,12.208,12.288,12.208,import,6,True
2016-05-30,12.256,12.272,12.384,12.304,12.32,12.336,12.224,12.416,12.352,12.16,...,12.576,12.704,12.48,11.76,12.064,12.048,12.368,import,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-05-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-08,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-06-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-06-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-06-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-06-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-06-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False

In [6]:
# weekend_data = billData[billData['weekend'] == True]
# weekday_data = billData[billData['weekend'] == False]
import_data = billData[billData['Import_Export'] == 'import']
export_data = billData[billData['Import_Export'] == 'export']

In [7]:
import_data.shape

(401, 51)

In [8]:
export_data = export_data[(export_data.index >= '2017/05/01') & (export_data.index <= '2017/05/30')]
import_data = import_data[(import_data.index >= '2017/05/01') & (import_data.index <= '2017/05/30')]

In [9]:
export_data

,00:00,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,20:30,21:00,21:30,22:00,22:30,23:00,23:30,Import_Export,weekday,weekend
2017-05-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-06,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-08,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False

In [10]:
def get_tariff_on_date_export(row):
    """
    This handles only weekends
    """
    if row['weekend']:
        return row[:'23:30'].apply(lambda each: float(each)) * 0.095
    else:
        return row[:'23:30'].apply(lambda each: float(each)) * 0.37

In [11]:
export_tariff = export_data.apply(lambda row: get_tariff_on_date_export(row), axis=1)

In [12]:
export_tariff

,00:00,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,19:00,19:30,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30
2017-05-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2017-05-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
def get_tariff_on_date_import(row):
    """
    This handles only weekends
    """
    if row['weekend']:
        return row[:'23:30'].apply(lambda each: float(each)) * 0.095
    else:
        r = row[:'23:30'].apply(lambda each: float(each))
        a = r['00:00': '06:30'] * 0.095
        b = r['07:00': '21:00'] * 0.37
        c = r['21:30': '23:30'] * 0.095
        return a.append(b).append(c)
#

In [14]:
import_tariff = import_data.apply(lambda row: get_tariff_on_date_import(row), axis=1)

In [15]:
import_tariff.values.sum()

4584.3947200000002

In [16]:
# value_each = import_tariff.sum() + 167.0 - export_tariff.sum()
tariff1 = (import_tariff.sum(axis=1) - export_tariff.sum(axis=1)).sum()

In [17]:
tariff1

4560.1643999999997

In [18]:
days_for_bill = import_tariff.index.values[-1] - import_tariff.index.values[0]

In [19]:
days_for_bill.astype('timedelta64[D]') / np.timedelta64(1, 'D')

29.0

In [20]:
ts = pd.to_datetime(str(import_tariff.index.values[0]))
ts.strftime('%d/%m/%Y')

'01/05/2017'

In [34]:
from influxdb import InfluxDBClient
import pandas as pd

client = InfluxDBClient('IP_Address', port, 'user', 'pass', 'dbname')
row = client.query("SELECT * FROM energy_consumption WHERE time >= '2017-05-01' AND time <= '2017-05-30'")
pv_data = pd.DataFrame.from_dict(list(row)[0]).drop(['ac_time', 'host', 'region'], axis=1)

In [35]:
pv_data['time'] =  pd.to_datetime(pv_data.time) + pd.DateOffset(hours=8)

In [36]:
offset = 0
def approximate_timestamp(each):
    global offset
    if abs(each.minute - offset) <= 5:
        offset ^= 30
        return each

In [37]:
pv_data['weekend'] = pv_data.time.dt.dayofweek.isin([5, 6])

In [38]:
pv_data['time'] = pv_data['time'].apply(approximate_timestamp)

In [39]:
pv_data_half_hourly = pv_data.dropna().reset_index().drop('index', axis = 1)

In [40]:
pv_data_half_hourly['generated_energy'] = pv_data_half_hourly.total_energy.diff(1)

In [41]:
pv_data_half_hourly.dropna(inplace=True)

In [42]:
def round_off_time(each):
    minOffset1 = abs(each.time.minute - 0)
    minOffset2 = abs(each.time.minute - 30)
    if minOffset1 < minOffset2:
        return '%4d-%02d-%02d T%02d:%02d' % (each.time.year, each.time.month, each.time.day, each.time.hour, 0)
    else:
        return '%4d-%02d-%02d T%02d:%02d' % (each.time.year, each.time.month, each.time.day, each.time.hour, 30)

In [43]:
pv_data_half_hourly['local_time'] = pv_data_half_hourly.apply(round_off_time, axis=1)
pv_data_half_hourly = pv_data_half_hourly[(pv_data_half_hourly.time >= '2017/05/03') & 
                                          (pv_data_half_hourly.time <= '2017/05/30')]
report_data = pv_data_half_hourly.drop(['weekend'], axis=1)
cols = ['time', 'local_time', 'total_energy', 'generated_energy', 'exported_energy (kwh)', 'consumed_unit']
report_data = report_data.loc[:, cols]
report_data.rename(index=str, columns={"total_energy": "cumulative_generated_energy (kwh)", 
                                       "generated_energy": "actual_generated_energy (kwh)", 
                                       "consumed_unit": "consumed_energy (kwh)"
                                      }, inplace=True)

In [44]:
def put_export_data(each):
    _date = each.local_time.split('T')[0]
    time = each.local_time.split('T')[-1]
    date = pd.to_datetime(_date).strftime('%Y-%m-%d')
    return export_data.loc[date, time]

report_data['exported_energy (kwh)'] = report_data.apply(put_export_data, axis=1)
report_data['exported_energy (kwh)'] = report_data['exported_energy (kwh)'].apply(float)
report_data['actual_generated_energy (kwh)'] = report_data['actual_generated_energy (kwh)'].apply(float)

# report_data['consumed_energy (kwh)'].apply(float)
report_data['consumed_energy (kwh)'] = report_data['actual_generated_energy (kwh)'] - report_data['exported_energy (kwh)']
#

In [45]:
report_data

,time,local_time,cumulative_generated_energy (kwh),actual_generated_energy (kwh),exported_energy (kwh),consumed_energy (kwh)
1,2017-05-03 10:25:21.530366240,2017-05-03 T10:30,6928,6.0,0.0,6.0
2,2017-05-03 11:00:28.675272097,2017-05-03 T11:00,6940,12.0,0.0,12.0
3,2017-05-03 11:25:32.290772731,2017-05-03 T11:30,6949,9.0,0.0,9.0
4,2017-05-03 12:00:37.701108788,2017-05-03 T12:00,6962,13.0,0.0,13.0
5,2017-05-03 12:25:41.018418268,2017-05-03 T12:30,6971,9.0,0.0,9.0
6,2017-05-03 13:00:50.403855296,2017-05-03 T13:00,6984,13.0,0.0,13.0
7,2017-05-03 13:25:53.679899831,2017-05-03 T13:30,6991,7.0,0.0,7.0
8,2017-05-03 14:00:59.394197844,2017-05-03 T14:00,7002,11.0,0.0,11.0
9,2017-05-03 14:26:02.103347714,2017-05-03 T14:30,7009,7.0,0.0,7.0
10,2017-05-03 15:01:05.940879766,2017-05-03 T15:00,7019,10.0,0.0,10.0
11,2017-05-03 15:26:08.535292184,2017-05-03 T15:30,7023,4.0,0.0,4.0
12,2017-05-03 16:01:11.526670058,2017-05-03 T16:00,7029,6.0,0.0,6.0
13,2017-05-03 16:26:13.898800856,2017-05-03 T16:30,7031,2.0,0.0,2.0
14,2017-05-03 17:01:17.772066274,2017-05-03 T17:00,7032,1.0,0.0,1.0
15,2017-05-03 17:26:20.433358343,2017-05-03 T17:30,7033,1.0,0.0,1.0
16,2017-05-03 18:01:23.977344916,2017-05-03 T18:00,7033,0.0,0.0,0.0
17,2017-05-03 18:26:26.638123623,2017-05-03 T18:30,7033,0.0,0.0,0.0
18,2017-05-03 19:01:29.664507764,2017-05-03 T19:00,7033,0.0,0.0,0.0
19,2017-05-03 19:26:32.345524688,2017-05-03 T19:30,7033,0.0,0.0,0.0
20,2017-05-03 20:01:35.552048092,2017-05-03 T20:00,7033,0.0,0.0,0.0
21,2017-05-03 20:26:38.126168279,2017-05-03 T20:30,7033,0.0,0.0,0.0
22,2017-05-03 21:01:41.546304903,2017-05-03 T21:00,7033,0.0,0.0,0.0
23,2017-05-03 21:26:44.135362371,2017-05-03 T21:30,7033,0.0,0.0,0.0
24,2017-05-03 22:01:47.822451472,2017-05-03 T22:00,7033,0.0,0.0,0.0
25,2017-05-03 22:26:50.461124820,2017-05-03 T22:30,7033,0.0,0.0,0.0
26,2017-05-03 23:01:53.970910671,2017-05-03 T23:00,7033,0.0,0.0,0.0
27,2017-05-03 23:26:56.689473847,2017-05-03 T23:30,7033,0.0,0.0,0.0
28,2017-05-04 00:02:00.178369653,2017-05-04 T00:00,7033,0.0,0.0,0.0
29,2017-05-04 00:27:02.929065465,2017-05-04 T00:30,7033,0.0,0.0,0.0
30,2017-05-04 01:02:06.976866371,2017-05-04 T01:00,7033,0.0,0.0,0.0
...,...,...,...,...,...,...
1192,2017-05-29 09:02:29.510225120,2017-05-29 T09:00,9728,5.0,0.0,5.0
1193,2017-05-29 09:27:36.746316903,2017-05-29 T09:30,9732,4.0,0.0,4.0
1194,2017-05-29 10:02:45.320307847,2017-05-29 T10:00,9741,9.0,0.0,9.0
1195,2017-05-29 10:27:52.014720788,2017-05-29 T10:30,9748,7.0,0.0,7.0
1196,2017-05-29 11:03:00.174300121,2017-05-29 T11:00,9759,11.0,0.0,11.0
1197,2017-05-29 11:28:05.366745880,2017-05-29 T11:30,9767,8.0,0.0,8.0
1198,2017-05-29 12:03:12.814914418,2017-05-29 T12:00,9779,12.0,0.0,12.0
1199,2017-05-29 12:28:18.920607345,2017-05-29 T12:30,9788,9.0,0.0,9.0
1200,2017-05-29 13:03:28.464640845,2017-05-29 T13:00,9800,12.0,0.0,12.0
1201,2017-05-29 13:28:34.171809647,2017-05-29 T13:30,9808,8.0,0.0,8.0
1202,2017-05-29 14:03:43.657801517,2017-05-29 T14:00,9819,11.0,0.0,11.0
1203,2017-05-29 14:28:50.199257583,2017-05-29 T14:30,9826,7.0,0.0,7.0
1204,2017-05-29 15:03:58.299115008,2017-05-29 T15:00,9834,8.0,0.0,8.0
1205,2017-05-29 15:29:06.163051647,2017-05-29 T15:30,9839,5.0,0.0,5.0
1206,2017-05-29 16:04:14.261241307,2017-05-29 T16:00,9844,5.0,0.0,5.0
1207,2017-05-29 16:29:19.415015132,2017-05-29 T16:30,9846,2.0,0.0,2.0
1208,2017-05-29 17:04:28.432381388,2017-05-29 T17:00,9847,1.0,0.0,1.0
1209,2017-05-29 17:29:33.738704238,2017-05-29 T17:30,9847,0.0,0.0,0.0
1210,2017-05-29 18:04:43.015793632,2017-05-29 T18:00,9847,0.0,0.0,0.0
1211,2017-05-29 18:29:48.005617884,2017-05-29 T18:30,9847,0.0,0.0,0.0
1212,2017-05-29 19:04:55.859244651,2017-05-29 T19:00,9847,0.0,0.0,0.0
1213,2017-05-29 19:25:06.037900614,2017-05-29 T19:30,9847,0.0,0.0,0.0
1214,2017-05-29 20:00:25.098169195,2017-05-29 T20:00,9847,0.0,0.0,0.0
1215,2017-05-29 20:25:38.179031412,2017-05-29 T20:30,9847,0.0,0.0,0.0
1216,2017-05-29 21:00:54.766965971,2017-05-29 T21:00,9847,0.0,0.0,0.0
1217,2017-05-29 21:26:07.733523091,2017-05-29 T21:30,9847,0.0,0.0,0.0
1218,2017-05-29 22:01:26.572678131,2017-05-29 T22:00,9847,0.0,0.0,0.0
1219,2017-05-29 22:26:40.173921668,2017-05-29 T22:30,9847,0.0,0.0,0.0
1220,2017-05-29 23:01:57.315382180,2017-05-29 T23:00,9847,0.0,0.0,0.0
1221,2017-05-29 23:27:10.195369645,2017-05-29 T23:30,9847,0.0,0.0,0.0

In [46]:
export_data

,00:00,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,20:30,21:00,21:30,22:00,22:30,23:00,23:30,Import_Export,weekday,weekend
2017-05-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-06,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-08,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False
2017-05-24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,2,False
2017-05-25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,3,False
2017-05-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,4,False
2017-05-27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,5,True
2017-05-28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,6,True
2017-05-29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,0,False
2017-05-30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,export,1,False

In [47]:
off_peak_energy1 = report_data[report_data.time.dt.weekday >= 5]['consumed_energy (kwh)'].sum()

In [48]:
weekday_data = report_data[report_data.time.dt.weekday < 5]

In [49]:
peak_energy = weekday_data[(weekday_data.time.dt.hour < 21) & (weekday_data.time.dt.hour >= 7)]['consumed_energy (kwh)'].sum()

In [50]:
off_peak_energy2 = weekday_data[~((weekday_data.time.dt.hour < 21) & (weekday_data.time.dt.hour >= 7))]['consumed_energy (kwh)'].sum()

In [51]:
peak_energy

2026.0

In [52]:
off_peak_energy1 + off_peak_energy2

643.94399999999996

In [53]:
report_data = report_data.drop(['time'], axis=1)
report_data.to_csv('May2017.csv')

In [54]:
report_data['actual_generated_energy (kwh)'].sum()

2925.0